### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by valkyrienyanko** [ValksGodotTools/Template#12]
### Mod Loader
- [ ] Handle dependency / incompatibility / game version / mod version / mod info logic
- [ ] Watch mod folder and listen for file changes and notify user that game needs to be restarted
- [ ] Figure out how to ignore scripts in mod assembly
- [ ] Figure out how to copy in duplicated scripts from mod assemblies (for e.g. 2 mods could have the same script in the same location)

**Comment by valkyrienyanko** [comment]
Comment Reserved for dumping.

Graphics setting can be retrieved like so `ProjectSettings.GetSetting("rendering/anti_aliasing/quality/msaa_3d")`

**Comment by valkyrienyanko** [comment]
## Template Reminders
Add the following to `Global.cs`
```cs
// _Ready()
UIConsole console = Global.Services.Get<UIConsole>();
Global.Services.Get<Logger>().MessageLogged += console.AddMessage;
```
```cs
public static void Log(object message) => Services.Get<Logger>().Log(message);
```
### Credits Scene
Add scroll?

### Pause
Set GetTree().Paused = true and false in UIPopupmenu script. Set UIPopupmenu script and all autoload scenes to process mode = always

on main menu btn pressed GetTree().Paused = false

### UIOptionsDisplay.cs

if (!GodotObject.IsInstanceValid(optionBtnWindowMode))
    return;

### Export options
Export (include) all *.txt

### CameraController
Add ZoomChanged event

### DebugOverlay
Add a debug overlay that displays FPS, object count, ram usage, and maybe other things

### Localization
Change "Licensed" to "licensed"

### Add blur to UIPopupMenu panel container
